#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y && sudo apt-get install -y nginx

service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
