#!/usr/bin/env bash
# Install nginx
# shellcheck disable=SC2154
sudo apt-get update -y && sudo apt-get install -y nginx

sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo service nginx start
